---
server_name: "localhost:8800"
signing_key_path: "/src/.buildkite/test.signing.key"
report_stats: false
trusted_key_servers:
  - server_name: "matrix.org"
suppress_key_server_warning: true

database:
  name: (( grab $.PROJECT.name ))
  args:
    # Make Usage of Spruce Operators
    user: (( grab $.SECRETS.database.user ))
    host: postgres
    password: (( grab $.SECRETS.database.user ))
    database: (( concat $.PROJECT.name "-" $.PROJECT.version ))
